### ISSUE TITLE
Readme file

### ISSUE THREAD

**Issue by mawada-sweis** [mawada-sweis/Clustering-Analysis#10]
# The Citywide Mobility Survey (CMS)
The Citywide Mobility Survey (CMS) is a survey conducted by the New York City Department of Transportation (DOT) to gather information about the travel behavior, preferences, and attitudes of New York City residents. The survey is conducted periodically, and the data collected is used to inform transportation planning and policy decisions.

## Table of Contents
* [Data Objectives](#data-objectives) 

* [Project Objectives](#project-objective)

## Data Objectives 
The primary objectives of the CMS data collection are:
* Identify the factors and experiences that drive transportation choices for New York City residents.
* Understand current views on the state of transportation within the City.
* Measure attitudes toward current transportation issues and topics in New York City.

## Project Objective
The objective of this project is to analyze the CMS dataset to gain insights into the travel behavior, preferences, and attitudes of New York City residents. Specifically, we aim to:

* Understand the relationship between residents' behaviors, preferences, attitudes, and traveling methods.
* Identify any trends or patterns in the data that may be relevant to transportation planning and policy decisions.

By achieving these objectives, we hope to contribute to the ongoing efforts to improve transportation in New York City and enhance the mobility of its residents.

**Comment by mawada-sweis** [comment]
Please edit the discription of the task on the project board, it’s redundant. Instead put what the Readme file contains.

Furthermore, you should be aware that we do not use all samples because one person from the same household fills out the survey (not all the persons in the same household).

In the last line, its better to say “between residents _behaviour/attitudes_ and methods”.

**Comment by mawada-sweis** [comment]
My question is, why is there a section called "data objectives"?

**Comment by zubaidasader** [comment]
Data objectives describe the goals of the survey and what the collected data aims to capture. Understanding the objectives is essential as it provides context to the data and helps in analyzing the dataset. so I think it's better to keep it.

**Comment by mawada-sweis** [comment]
Got it
